In [1]:
import numpy as np

### Exercice 1:
Create a 1-dimensional NumPy array with 5 integers from 0 to 4.

In [3]:
arr = np.arange(5); arr

array([0, 1, 2, 3, 4])

 ### Exercice 2:
 Create a 2-dimensional NumPy array with shape (2, 3) containing only ones.

In [4]:
arr = np.ones((2,3)); arr

array([[1., 1., 1.],
       [1., 1., 1.]])

### Exercice 3:
Create a 3-dimensional NumPy array with shape (2, 3, 4) containing only zeros.

In [9]:
arr = np.zeros((2,3,4)); arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
arr.shape

(2, 3, 4)

### Exercice 4:
Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 0 and 9.

In [23]:
#random.randint(low, high=None, size=None, dtype=int)
arr = np.random.randint(9, size=(3, 4)) ; arr

array([[8, 0, 4, 0],
       [8, 7, 0, 1],
       [3, 8, 2, 4]])

In [24]:
type(arr)

numpy.ndarray

### Exercice 5:
Create a 2-dimensional NumPy array with shape (3, 4) and find its dimensions and size.

In [27]:
arr = np.array((3,4))
arr.shape
arr.size

2

### Exercice 6:
Create a 2-dimensional NumPy array with shape (3, 4) and calculate the sum of all its elements.

In [29]:
arr = np.array((3,4))
np.sum(arr)

7

### Exercice 7:
Create a 2-dimensional NumPy array with shape (3, 4) and find the minimum and maximum value in each row.

In [31]:
arr = np.array((3,4))
np.min(arr)

3

In [32]:
np.max(arr)

4

### Exercice 8:
Create a 2-dimensional NumPy array with shape (3, 4) and replace all the odd numbers with -1.

In [33]:
arr = np.array((3,4))

In [34]:
arr

array([3, 4])

### Exercice 9:
Create a 2-dimensional NumPy array with shape (3, 4) and extract the elements in the second and third row and the second and third column.

In [ ]:
arr = np.array((3,4))

### Exercice 10:
Create a 2-dimensional NumPy array with shape (3, 4) and multiply each element by 2.

In [35]:
arr = np.array((3,4))
print(arr*2)

[6 8]
